const bdInitialProfs =[{"id":1,"nom":"Nelle","prenom":"Keene","adresse":"098 Delladonna Drive","photo":"👩🏽"},
{"id":2,"nom":"Ricky","prenom":"Alair","adresse":"26463 Comanche Center","photo":"﻿"},
{"id":3,"nom":"Esra","prenom":"Afton","adresse":"0 Elka Junction","photo":"␢"},
{"id":4,"nom":"Raymund","prenom":"Bridget","adresse":"688 Porter Trail","photo":"!@#$%^&*()"},
{"id":5,"nom":"Bary","prenom":"Hephzibah","adresse":"1 Oxford Park","photo":"\"'\"'\"''''\""},
{"id":6,"nom":"Glad","prenom":"Alister","adresse":"88 Hollow Ridge Point","photo":"-1E2"},
{"id":7,"nom":"Grace","prenom":"Cheslie","adresse":"92 West Terrace","photo":"1.00"},
{"id":8,"nom":"Sydney","prenom":"Darn","adresse":"124 Ronald Regan Center","photo":"⁦test⁧"},
{"id":9,"nom":"Sile","prenom":"Dacy","adresse":"03664 Caliangt Pass","photo":"Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣"},
{"id":10,"nom":"Gerhard","prenom":"Jacquelynn","adresse":"52 Namekagon Way","photo":"❤️ 💔 💌 💕 💞 💓 💗 💖 💘 💝 💟 💜 💛 💚 💙"},
{"id":11,"nom":"Pippo","prenom":"Meta","adresse":"4466 Vahlen Junction","photo":"⁰⁴⁵₀₁₂"},
{"id":12,"nom":"Perle","prenom":"Melesa","adresse":"9 Homewood Place","photo":"̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕"},
{"id":13,"nom":"Jamill","prenom":"Nance","adresse":"249 Garrison Park","photo":"הָיְתָהtestالصفحات التّحول"},
{"id":14,"nom":"Lizette","prenom":"Rog","adresse":"6 Ilene Trail","photo":"NIL"},
{"id":15,"nom":"Nevile","prenom":"Windham","adresse":"3 Waubesa Plaza","photo":"() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }"},
{"id":16,"nom":"Marcellus","prenom":"Merola","adresse":"956 Towne Place","photo":"‫test‫"},
{"id":17,"nom":"Bruce","prenom":"Lesya","adresse":"859 1st Crossing","photo":"1E2"},
{"id":18,"nom":"Mandi","prenom":"Lara","adresse":"08 Sloan Crossing","photo":"ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ"},
{"id":19,"nom":"Eldredge","prenom":"Rakel","adresse":"8 Reinke Hill","photo":"åß∂ƒ©˙∆˚¬…æ"},
{"id":20,"nom":"Nelli","prenom":"Desiree","adresse":"6096 6th Center","photo":"1"}]

export {bdInitialProfs}